name: Release CI

on:
    push:
        paths-ignore:
            - "CODE_OF_CONDUCT.md"
            - "CONTRIBUTING.md"
            - "README.md"
            - "LICENSE"
        branches:
            - master
jobs:
    build_job:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        name: 'Build job'
        steps:
            - uses: actions/checkout@v2

            - name: 'Use Node.js 12.16.3'
              uses: actions/setup-node@v1
              with:
                node-version: 12.16.3

            - name: 'Install npm dependencies'
              id: npmci
              run: npm ci
            
            - name: 'Run tests'
              id: npmruntest
              run: npm run test
