name: Release CI

on:
    push:
        paths-ignore:
            - "CODE_OF_CONDUCT.md"
            - "CONTRIBUTING.md"
            - "README.md"
            - "LICENSE"
        branches:
            - master
jobs:
    build_and_release_package_job:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        name: 'Build & Release package'
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: 'Use Node.js 12.16.3'
              uses: actions/setup-node@v1
              with:
                node-version: 12.16.3

            - name: 'Install npm dependencies'
              id: npmci
              run: npm ci
            
            - name: 'Run tests'
              id: npmruntest
              run: npm run test

            - name: 'Build'
              id: npmrunbuild
              run: npm run build

            - name: 'Release'
              id: npmrunrelease
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm run release

